"""fix: set birthday not required in UserAlchemy model

Revision ID: 34e02f261d9c
Revises: bc5e371dee4e
Create Date: 2023-05-19 12:04:15.852453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e02f261d9c'
down_revision = 'bc5e371dee4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
